const funnyQuotes: string[] = [
    "I can't believe I got fired from the calendar factory. All I did was take a day off!",
    "Age is merely the number of years the world has been enjoying you. - Unknown",
    "Before you criticize someone, you should walk a mile in their shoes. That way, when you criticize them, you’re a mile away and you have their shoes!",
    "A clear conscience is usually the sign of a bad memory. - Steven Wright",
    "I used to think I was indecisive, but now I'm not so sure.",
    "The early bird might get the worm, but the second mouse gets the cheese. - Steven Wright",
    "I'm on a seafood diet. I see food, and I eat it.",
    "The problem with the gene pool is that there is no lifeguard.",
    "To be old and wise, you must first be young and stupid. - Unknown",
    "He who laughs last didn't get the joke.",
    "A man is known by the company he keeps, and the food he orders. - Unknown",
    "I'm not arguing; I'm just explaining why I'm right.",
    "If you think nobody cares if you’re alive, try missing a couple of payments. - Earl Wilson",
    "Some people are like clouds. When they disappear, it’s a beautiful day.",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "You know you’re getting old when the candles cost more than the cake.",
    "I’ve got a friend who’s a knight. He says he’s on a quest for the Holy Grail. I told him, 'Good luck! I hear it’s a bit hard to find, but you could always settle for a pint of ale!'",
    "Why do they call it a knight’s armor? Because when they take it off, they’re just a little *rusty*!",
    "A jester’s job is to make you laugh, but I find that my face alone does the trick quite well!",
    "Why did the knight get kicked out of the tavern? Because he was always raising his sword and never his glass!",
    "Why did the medieval baker go to jail? Because he got caught kneading dough!",
    "Why did the knight refuse to fight? He didn't have the guts... or the armor... or the sword!",
    "In the realm of jesters, be careful—what you think is a jest might just be a deadly roast!",
    "If you want to know if a knight is brave, just ask him how many times he's faced the dragon... and then ask his therapist!",
    "A squire walks into a tavern and says, 'I’ll have a pint of your finest ale!' The bartender replies, 'That'll be a gold piece!' The squire retorts, 'Fine! But I shall return with a dragon’s hoard!'",
    "Why don’t medieval knights ever get lost? Because they always *sword* by their map!"
  ];
  export default funnyQuotes;
